<?php
session_start();

if(isset($_SESSION['admin']))
{
    $USER = $_SESSION['admin'];

} else {

    header('location:index.php?page=login');

}
    include_file('templates/header');
    include_file('pages/sidebar');
    include_file('pages/topbar');

?>


<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <a href="<?php echo URL('administrator_dashboard&stn='.$_SESSION['admin']->station); ?>"  class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="bi bi-arrow-left-circle"></i> Back
    </a>
</div>

<div class="row">
    <div class="col-lg-12 d-none d-lg-block bg-register-image"></div>
    <div class="col-lg-12">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Add Product</h1>
                <br>
            </div>
            
            <form class="user" method="POST" action="<?php echo URL('add_product');?>">
                
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" class="form-control form-control-user" id="pname" name="pname" placeholder="Product Name" required>
                    </div>
                    <div class="col-sm-6">
                        <input type="text" class="form-control form-control-user" id="price" name="price" placeholder="Product Price" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="number" class="form-control form-control-user" id="kg" name="kg" placeholder="Product KG's">
                    </div>
                    <div class="col-sm-6">
                        <input type="number" class="form-control form-control-user" id="qty" name="qty" placeholder="Product Quantity">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <input type="text" class="form-control form-control-user" id="img" name="img" placeholder="Product Image Name" required>
                        <small class="text-warning mx-3"><b>Example:</b> gas_cooker.jpg</small>
                    </div>
                    <div class="col-sm-6">
                        <input type="text" class="form-control form-control-user" value="<?php echo $USER->station;?>" disabled>
                        <input type="hidden" name="station" value="<?php echo $USER->station;?>">
                        <small class="text-warning mx-3"><b>NOTE:</b> Product station</small>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-user" value="<?php echo generate_serial_number();?>" disabled>
                        <input type="hidden" name="snum" value="<?php echo generate_serial_number();?>">
                        <small class="text-warning mx-3"><b>NOTE:</b> AUTOGENERATED SERIAL NUMBER</small>
                    </div>
                </div>
                <div class="form-group">
                    <textarea type="text" class="form-control form-control-user" id="description" name="description" placeholder="Product Description" required></textarea>
                </div>
                <button type="submit" name="addProduct" class="btn w-50 btn-primary btn-user btn-sm">
                    <i class="bi bi-plus-circle"></i>    
                    Add
                </button>
                
            </form>
            <hr>
        </div>
    </div>
                </div>



                <?php 
    
if(isset($data['alert'])){?>
    <script>
        Swal.fire({
            icon: '<?php echo $data['icon'];?>',
            title: '<?php echo $data['title'];?>',
            text: '<?php echo $data['alert'];?>'
        });
    </script>
<?php }?>


<?php include_file('templates/footer');?>